spring:
  profiles:
    group:
      local: common, domain, infra, security
      dev: common, domain, infra, security

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev

server:
  tomcat:
    keep-alive-timeout: 70