spring:
  profiles:
    group:
      local: common, domain, infra, security
      dev: common, domain, infra, security

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    import: api-variable.yaml
    activate:
      on-profile: dev

server:
  tomcat:
    keep-alive-timeout: 70
  ssl:
    enabled: true
    key-alias: tomcat-localhost
    key-password: ${key.password}
    key-store: classpath:keystore.jks
    key-store-type: PKCS12
    key-store-password: ${key.password}
    key-store-provider: SUN