spring:
  profiles:
    group:
      local: common, domain, infra, security
      dev: common, domain, infra, security

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    import: api-variable.yaml
    activate:
      on-profile: dev

server:
  tomcat:
    keep-alive-timeout: 70
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.jks
#    key-store-password: alsdn1
#    key-alias: tomcat
#    key-store-type: JKS
#  port: 8080
#    key-password: ${key.password}
#    key-store-provider: SUN