spring:
  config:
    activate:
      on-profile: local
    import: domain-variable.yaml
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      data-locations: classpath:sql/data.sql
      mode: always
---
spring:
  config:
    activate:
      on-profile: dev