spring:
  config:
    import: common-variable.yaml
    activate:
      on-profile: local

github-pages:
  url: ${github-pages.url}
---
spring:
  config:
    activate:
      on-profile: dev

github-pages:
  url: ${GIT_HUB_PAGES_URL}